### ISSUE TITLE
How to prevent this in Mods?

### ISSUE THREAD

**Issue by NameLord** [steviegt6/fnb#42]
I have these but still it doesn't seem to, its still extracting the .dll isn't a way to block that?
```
hideCode = true
hideResources = true
includeSource = false
```
Because i want to test with people and i don't want to let them play around and steal.
Edit:1 The Tmodloader when i extract my mod it respects those 3 lines of code..

**Comment by steviegt6** [comment]
You can't prevent it. This is intentional.
